sources:
  - name: lab-cisco
    hosts:
      - url: 'ssh://networklab.ops.orb.live'
devices:
  - name: cisco_ios_device
    transport: ssh
    ignore-known-hosts: true
    slow-host: true
auths:
  - name: cisco
    username: USERNAME
    password: 'plain:PASSWORD'
namespaces:
  - name: lab
    source: lab-cisco
    device: cisco_ios_device
    auth: cisco
